$:.unshift(File.expand_path("../tictactoe/", __FILE__))
$:.unshift(File.expand_path("../../", __FILE__))
require 'board'
require 'gameloop'
require 'player'
require 'computer'
require 'board_printer'
require 'game'
require 'human'
require 'scorer'
require 'webttt'
